In [1]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score
from sklearn.preprocessing import StandardScaler

In [2]:
data = {
    'age' : [12,34,23,34,56,45,56,34],
    'spend' : [2000,30000,40000,5000,5000,20000,10000,12000]
}

frame = pd.DataFrame(data)

In [3]:
frame.head(10)

   age  spend
0   12   2000
1   34  30000
2   23  40000
3   34   5000
4   56   5000
5   45  20000
6   56  10000
7   34  12000

In [4]:
scaler = StandardScaler()

In [5]:
scaling = scaler.fit_transform(frame)

In [6]:
model = KMeans(n_clusters = 2,random_state = 42)

In [7]:
m = model.fit(scaling)
print(m)

KMeans(n_clusters=2, random_state=42)

In [8]:
labels = m.labels_

i = len(labels)

add= []
for j in range(0,i):
    add.append("Cluster 1" if labels[j] == 0 else "Cluster 2")

In [9]:
# Metrics

In [10]:
print(silhouette_score(frame,labels))

0.6413408731318166

In [11]:
print(davies_bouldin_score(frame,labels))

0.38461696886250585

In [12]:
print(calinski_harabasz_score(frame,labels))

23.22124951047981

In [13]:
frame["Cluster"] = add
frame

   age  spend    Cluster
0   12   2000  Cluster 2
1   34  30000  Cluster 1
2   23  40000  Cluster 1
3   34   5000  Cluster 2
4   56   5000  Cluster 2
5   45  20000  Cluster 2
6   56  10000  Cluster 2
7   34  12000  Cluster 2