In [8]:
from sklearn.decomposition import PCA
import pandas as pd

In [7]:
data = {
    "x" : [2.5,0.5,2.2,1.9,3.1],
    "y" : [2.4,0.7,2.9,2.2,3.0]
}

In [9]:
call = pd.DataFrame(data)

In [10]:
call

     x    y
0  2.5  2.4
1  0.5  0.7
2  2.2  2.9
3  1.9  2.2
4  3.1  3.0

In [15]:
model = PCA(n_components=1,random_state=42)

In [26]:
result = model.fit_transform(call)

In [27]:
print(model)

PCA(n_components=1, random_state=42)

In [28]:
print(f"Variance Ratio : ",model.explained_variance_ratio_) # how much variance is explained

Variance Ratio :  [0.96989047]

In [29]:
print(model.components_) # eigenvector (principal component direction)

[[0.72474155 0.68902082]]

In [30]:
model.mean_

array([2.04, 2.24])

In [31]:
call["PC"] = result

In [32]:
call

     x    y        PC
0  2.5  2.4  0.443624
1  0.5  0.7 -2.177194
2  2.2  2.9  0.570712
3  1.9  2.2 -0.129025
4  3.1  3.0  1.291882